Traceback (most recent call last):
  File "c:\Users\david.moragarces\vsworkspace\automate_the_boring_stuff\_11_Debugging\_34_traceback.py", line 3, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
